# Generated by Django 3.1.7 on 2021-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='M', max_length=10)),
                ('profileimg', models.ImageField(default='', upload_to='profiles/')),
                ('phone_no', models.CharField(default='+91', max_length=14, null=True)),
                ('address', models.CharField(default='Tirupathi', max_length=200)),
            ],
        ),
    ]
